### ISSUE TITLE
Hello, sir. Please teach me how to solve this.

### ISSUE THREAD

**Issue by uparupaNFT** [zobront/nft-snapshot#2]
Token 2 Error:
Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.6.1)
    at Logger.makeError (C:\Users\82103\Desktop\nft-snapshot\nft-snapshot-main\node_modules\@ethersproject\logger\lib\index.js:233:21)
    at Logger.throwError (C:\Users\82103\Desktop\nft-snapshot\nft-snapshot-main\node_modules\@ethersproject\logger\lib\index.js:242:20)
    at JsonRpcProvider.<anonymous> (C:\Users\82103\Desktop\nft-snapshot\nft-snapshot-main\node_modules\@ethersproject\providers\lib\json-rpc-provider.js:517:54)
    at step (C:\Users\82103\Desktop\nft-snapshot\nft-snapshot-main\node_modules\@ethersproject\providers\lib\json-rpc-provider.js:48:23)
    at Object.throw (C:\Users\82103\Desktop\nft-snapshot\nft-snapshot-main\node_modules\@ethersproject\providers\lib\json-rpc-provider.js:29:53)
    at rejected (C:\Users\82103\Desktop\nft-snapshot\nft-snapshot-main\node_modules\@ethersproject\providers\lib\json-rpc-provider.js:21:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'could not detect network',
  code: 'NETWORK_ERROR',
  event: 'noNetwork'
}

**Comment by zobront** [comment]
What chain ID are you using?

**Comment by uparupaNFT** [comment]
Hello
im using polygon chain, number 137!
​
-----Original Message-----

**Comment by zobront** [comment]
Is your provider endpoint from Infura / Alchemy set up for Polygon?

If you share your code I can take a look.

**Comment by uparupaNFT** [comment]
Sorry for late reply.
i used alchemy, and puted http adress in visual studio program.
please check my image.
do i have to insert websockets?
thank you!
 
-----Original Message-----

**Comment by uparupaNFT** [comment]
tried with eth mainnet
 
-----Original Message-----

**Comment by zobront** [comment]
No image attached. You just put the HTTP link from Alchemy as the PROVIDER_ENDPOINT. If you send the code I can help, but otherwise I'll close this.

**Comment by uparupaNFT** [comment]
const ethers = require("ethers")
const createCsvWriter = require('csv-writer').createObjectCsvWriter;

const TOKEN_ADDRESS = "0x2953399124F0cBB46d2CbACD8A89cF0599974963"; // INSERT
const STARTING_TOKEN_ID = 1;
const HIGHEST_TOKEN_ID = 1000; // INSERT
const PROVIDER_ENDPOINT = "https://eth-mainnet.alchemyapi.io/v2/74WTJvHjOrUwehy7SsSwVkvWtITCITET"; // INSERT
const CHAIN_ID = 137;
const FORMAT = "tokensByOwner"; // options: "tokensByOwner" or "ownerByTokenId"

const provider = new ethers.providers.JsonRpcProvider(PROVIDER_ENDPOINT, CHAIN_ID);
const abi = ["function ownerOf (uint256) view returns (address)"];
const contract = new ethers.Contract(TOKEN_ADDRESS, abi, provider);

Token 27 Error:
Error: underlying network changed (event="changed", network={"name":"matic","chainId":137,"ensAddress":null,"_defaultProvider":null}, detectedNetwork={"name":"homestead","chainId":1,"ensAddress":"0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"}, code=NETWORK_ERROR, version=providers/5.6.1)
    at Logger.makeError ***@***.***\logger\lib\index.js:233:21)
    at JsonRpcProvider.<anonymous> ***@***.***\providers\lib\base-provider.js:1175:40)
    at step ***@***.***\providers\lib\base-provider.js:48:23)
    at Object.next ***@***.***\providers\lib\base-provider.js:29:53)
    at fulfilled ***@***.***\providers\lib\base-provider.js:20:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'underlying network changed',
  code: 'NETWORK_ERROR',
  event: 'changed',
  network: {
    name: 'matic',
    chainId: 137,
    ensAddress: null,
    _defaultProvider: null
  },
  detectedNetwork: {
    name: 'homestead',
    chainId: 1,
    ensAddress: '0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e',
    _defaultProvider: [Function: func] { renetwork: [Function (anonymous)] }
  }
}
 
This is when i used eth mainnet http
 
const ethers = require("ethers")
const createCsvWriter = require('csv-writer').createObjectCsvWriter;

const TOKEN_ADDRESS = "0x2953399124F0cBB46d2CbACD8A89cF0599974963"; // INSERT
const STARTING_TOKEN_ID = 1;
const HIGHEST_TOKEN_ID = 1000; // INSERT
const PROVIDER_ENDPOINT = "https://polygon-mainnet.g.alchemy.com/v2/dOCze8XbPcPgWLRJ5SANtPzyFPWsyaZT"; // INSERT
const CHAIN_ID = 137;
const FORMAT = "tokensByOwner"; // options: "tokensByOwner" or "ownerByTokenId"
Token 3 Error:
Error: missing revert data in call exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":47,\"error\":{\"code\":-32000,\"message\":\"execution reverted\"}}","error":{"code":-32000},"requestBody":"{\"method\":\"eth_call\",\"params\":[{\"to\":\"0x2953399124f0cbb46d2cbacd8a89cf0599974963\",\"data\":\"0x6352211e0000000000000000000000000000000000000000000000000000000000000003\"},\"latest\"],\"id\":47,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://polygon-mainnet.g.alchemy.com/v2/dOCze8XbPcPgWLRJ5SANtPzyFPWsyaZT"}, data="0x", code=CALL_EXCEPTION, version=providers/5.6.1)
    at Logger.makeError ***@***.***\logger\lib\index.js:233:21)
    at Logger.throwError ***@***.***\logger\lib\index.js:242:20)
    at checkError ***@***.***\providers\lib\json-rpc-provider.js:76:16)       
    at JsonRpcProvider.<anonymous> ***@***.***\providers\lib\json-rpc-provider.js:659:47)
    at step ***@***.***\providers\lib\json-rpc-provider.js:48:23)
    at Object.throw ***@***.***\providers\lib\json-rpc-provider.js:29:53)     
    at rejected ***@***.***\providers\lib\json-rpc-provider.js:21:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'missing revert data in call exception',
  code: 'CALL_EXCEPTION',
  error: Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":47,\"error\":{\"code\":-32000,\"message\":\"execution reverted\"}}", error={"code":-32000}, requestBody="{\"method\":\"eth_call\",\"params\":[{\"to\":\"0x2953399124f0cbb46d2cbacd8a89cf0599974963\",\"data\":\"0x6352211e0000000000000000000000000000000000000000000000000000000000000003\"},\"latest\"],\"id\":47,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://polygon-mainnet.g.alchemy.com/v2/dOCze8XbPcPgWLRJ5SANtPzyFPWsyaZT", code=SERVER_ERROR, version=web/5.6.0)
      at Logger.makeError ***@***.***\logger\lib\index.js:233:21)
      at Logger.throwError ***@***.***\logger\lib\index.js:242:20)
      at ***@***.***\web\lib\index.js:305:32
      at step ***@***.***\web\lib\index.js:33:23)
      at Object.next ***@***.***\web\lib\index.js:14:53)
      at fulfilled ***@***.***\web\lib\index.js:5:58)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    reason: 'processing response error',
    code: 'SERVER_ERROR',
    body: '{"jsonrpc":"2.0","id":47,"error":{"code":-32000,"message":"execution reverted"}}',
    error: Error: execution reverted
        at getResult ***@***.***\providers\lib\json-rpc-provider.js:142:21)   
        at processJsonFunc ***@***.***\web\lib\index.js:348:22)
        at ***@***.***\web\lib\index.js:280:46
        at step ***@***.***\web\lib\index.js:33:23)
        at Object.next ***@***.***\web\lib\index.js:14:53)
        at fulfilled ***@***.***\web\lib\index.js:5:58)
        at processTicksAndRejections (node:internal/process/task_queues:96:5) {
      code: -32000,
      data: undefined
    },
    requestBody: '{"method":"eth_call","params":[{"to":"0x2953399124f0cbb46d2cbacd8a89cf0599974963","data":"0x6352211e0000000000000000000000000000000000000000000000000000000000000003"},"latest"],"id":47,"jsonrpc":"2.0"}',
    requestMethod: 'POST',
    url: 'https://polygon-mainnet.g.alchemy.com/v2/dOCze8XbPcPgWLRJ5SANtPzyFPWsyaZT'
  },
  data: '0x'
}
This is when i used polygon mainnet http 
-----Original Message-----
